compressionLevel: mixed

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistries:
  '//npm.pkg.github.com':
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN:-}'

npmPublishRegistry: 'http://localhost:4873/'

yarnPath: .yarn/releases/yarn-4.10.3.cjs
