import { type OBSERVATION_INTERPRETATION } from '@openmrs/esm-patient-common-lib';
import { GroupedObservation } from '../packages/esm-patient-tests-app/src/types';

export const mockBasePanel: GroupedObservation = {
  key: 'Hematology',
  date: '2024-01-01T10:00:00Z',
  flatName: 'Hematology',
  entries: [
    {
      conceptUuid: 'cbc-uuid',
      datatype: 'numeric',
      display: 'Complete Blood Count',
      lowAbsolute: 0,
      lowNormal: 100,
      units: 'g/dL',
      lowCritical: 80,
      hiNormal: 150,
      flatName: 'Hematology-Complete Blood Count',
      hasData: true,
      range: '100-150',
      obsDatetime: '2024-01-01T10:00:00Z',
      value: '120',
      interpretation: 'NORMAL' as OBSERVATION_INTERPRETATION,
      key: 'test-key',
    },
    {
      conceptUuid: 'hematocrit-uuid',
      datatype: 'numeric',
      display: 'Hematocrit',
      lowAbsolute: 0,
      lowNormal: 35,
      units: '%',
      lowCritical: 20,
      hiNormal: 45,
      flatName: 'Hematology-Hematocrit',
      hasData: true,
      range: '35-45',
      obsDatetime: '2024-01-01T10:00:00Z',
      value: '50',
      interpretation: 'HIGH' as OBSERVATION_INTERPRETATION,
      key: 'test-key',
    },
    {
      conceptUuid: 'hemoglobin-uuid',
      datatype: 'numeric',
      display: 'Hemoglobin',
      lowAbsolute: 0,
      lowNormal: 12,
      units: 'g/dL',
      lowCritical: 10,
      hiNormal: 16,
      flatName: 'Hematology-Hemoglobin',
      hasData: true,
      range: '12-16',
      obsDatetime: '2024-01-01T10:00:00Z',
      value: '8',
      interpretation: 'LOW' as OBSERVATION_INTERPRETATION,
      key: 'test-key',
    },
  ],
};
