import React from 'react';
import { Form, Formik } from 'formik';
import { screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { getDefaultsFromConfigSchema, useConfig } from '@openmrs/esm-framework';
import { type AddressTemplate, type IdentifierSource } from '../../patient-registration.types';
import { mockIdentifierTypes, mockOpenmrsId, mockPatient, mockSession } from '__mocks__';
import { renderWithContext } from 'tools';
import { esmPatientRegistrationSchema, type RegistrationConfig } from '../../../config-schema';
import { type Resources } from '../../../offline.resources';
import {
  PatientRegistrationContextProvider,
  type PatientRegistrationContextProps,
} from '../../patient-registration-context';
import { Identifiers, setIdentifierSource } from './id-field.component';
import { ResourcesContextProvider } from '../../../resources-context';

const mockUseConfig = jest.mocked(useConfig<RegistrationConfig>);

const mockResourcesContextValue = {
  addressTemplate: null as unknown as AddressTemplate,
  currentSession: mockSession.data,
  identifierTypes: [],
  relationshipTypes: { results: [] },
} as Resources;

const mockInitialFormValues = {
  additionalFamilyName: '',
  additionalGivenName: '',
  additionalMiddleName: '',
  addNameInLocalLanguage: false,
  address: {},
  birthdate: null,
  birthdateEstimated: false,
  deathCause: '',
  deathDate: '',
  familyName: 'Doe',
  gender: 'male',
  givenName: 'John',
  identifiers: mockOpenmrsId,
  isDead: false,
  middleName: 'Test',
  monthsEstimated: 0,
  patientUuid: mockPatient.uuid,
  relationships: [],
  telephoneNumber: '',
  yearsEstimated: 0,
};

const mockContextValues: PatientRegistrationContextProps = {
  currentPhoto: null,
  inEditMode: false,
  identifierTypes: [],
  initialFormValues: mockInitialFormValues,
  isOffline: false,
  setCapturePhotoProps: jest.fn(),
  setFieldValue: jest.fn(),
  setInitialFormValues: jest.fn(),
  validationSchema: null,
  values: mockInitialFormValues,
} as unknown as PatientRegistrationContextProps;

/**
 * Helper to render Identifiers component with Formik.
 */
function renderIdentifiers(
  contextValues: PatientRegistrationContextProps = mockContextValues,
  resourcesContextValue: Resources = mockResourcesContextValue,
) {
  return renderWithContext(
    <Formik initialValues={{}} onSubmit={() => {}}>
      <Form>
        <PatientRegistrationContextProvider value={contextValues}>
          <Identifiers />
        </PatientRegistrationContextProvider>
      </Form>
    </Formik>,
    ResourcesContextProvider,
    resourcesContextValue,
  );
}

describe('Identifiers component', () => {
  beforeEach(() => {
    mockUseConfig.mockReturnValue({
      ...getDefaultsFromConfigSchema(esmPatientRegistrationSchema),
      defaultPatientIdentifierTypes: ['OpenMRS ID'],
    });
    mockResourcesContextValue.identifierTypes = [];
  });

  describe('Loading state', () => {
    it('renders loading skeleton when identifier types are not available', () => {
      renderIdentifiers();

      expect(screen.getByRole('progressbar')).toBeInTheDocument();
    });
  });

  describe('Rendering', () => {
    it('renders identifier inputs when identifier types are loaded', () => {
      mockResourcesContextValue.identifierTypes = mockIdentifierTypes;
      renderIdentifiers();

      expect(screen.getByText('Identifiers')).toBeInTheDocument();
      const configureButton = screen.getByRole('button', { name: 'Configure' });
      expect(configureButton).toBeInTheDocument();
      expect(configureButton).toBeEnabled();
    });

    it('renders default identifier types', () => {
      mockResourcesContextValue.identifierTypes = mockIdentifierTypes;
      renderIdentifiers();

      // OpenMRS ID should be rendered as it's in defaultPatientIdentifierTypes
      // The identifier might be auto-generated (hidden) or visible
      const identifierInput = screen.queryByLabelText(/openmrs id/i);
      const autoGeneratedPlaceholder = screen.queryByTestId('identifier-placeholder');
      expect(identifierInput || autoGeneratedPlaceholder).toBeTruthy();
    });
  });

  describe('User interaction', () => {
    it('opens identifier selection overlay when Configure button is clicked', async () => {
      const user = userEvent.setup();
      mockResourcesContextValue.identifierTypes = mockIdentifierTypes;
      renderIdentifiers();

      const configureButton = screen.getByRole('button', { name: 'Configure' });
      await user.click(configureButton);

      await waitFor(() => {
        expect(screen.getByRole('button', { name: 'Close overlay' })).toBeInTheDocument();
      });
    });
  });
});

describe('setIdentifierSource utility', () => {
  describe('Auto-generation behavior', () => {
    it('returns auto-generated as identifier value when auto-generation is enabled and manual entry is disabled', () => {
      const identifierSource = {
        autoGenerationOption: {
          automaticGenerationEnabled: true,
          manualEntryEnabled: false,
        },
      } as IdentifierSource;
      const result = setIdentifierSource(identifierSource, '', '');
      expect(result.identifierValue).toBe('auto-generated');
      expect(result.autoGeneration).toBe(true);
    });

    it('returns provided identifier value when manual entry is enabled', () => {
      const identifierSource = {
        autoGenerationOption: {
          automaticGenerationEnabled: true,
          manualEntryEnabled: true,
        },
      } as IdentifierSource;
      const result = setIdentifierSource(identifierSource, '10001V', '');
      expect(result.identifierValue).toBe('10001V');
      expect(result.autoGeneration).toBe(true);
    });

    it('returns initial value when identifier value is auto-generated and manual entry is enabled', () => {
      const identifierSource = {
        autoGenerationOption: {
          automaticGenerationEnabled: true,
          manualEntryEnabled: true,
        },
      } as IdentifierSource;
      const result = setIdentifierSource(identifierSource, 'auto-generated', 'initial-value');
      expect(result.identifierValue).toBe('initial-value');
    });
  });
});
