import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev3.openmrs.org/openmrs/spa/patient/06238cb3-01f7-47d2-be9d-0625ea72ec75/chart/Conditions');
  await page.goto('https://dev3.openmrs.org/openmrs/spa/login');
  await page.getByLabel('Username').fill('admin');
  await page.getByLabel('Username').press('Enter');
  await page.getByLabel('Password').fill('Admin123');
  await page.getByLabel('Password').press('Enter');
  await page.locator('label').filter({ hasText: 'Outpatient Clinic' }).locator('span').first().click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.goto('https://dev3.openmrs.org/openmrs/spa/patient/06238cb3-01f7-47d2-be9d-0625ea72ec75/chart/Conditions');
  await page.getByText('Record conditions').click();
  await page.getByPlaceholder('Search conditions').click();
  await page.getByPlaceholder('Search conditions').fill('mental');
  await page.getByRole('menuitem', { name: 'Mental status change' }).click();
  await page.getByLabel('Onset date').click();
  await page.getByLabel('Onset date').fill('10/07/2023');
  await page.getByLabel('Onset date').press('Tab');
  await page.getByRole('button', { name: 'Save & close' }).click();
  await page.getByRole('button', { name: 'Edit or delete condition' }).click();
  await page.getByRole('menuitem', { name: 'Edit' }).click();
  await page.locator('label').filter({ hasText: 'Inactive' }).click();
  await page.getByLabel('End date').click();
  await page.getByLabel('End date').fill('11/07/2023');
  await page.getByLabel('End date').press('Tab');
  await page.getByRole('button', { name: 'Save & close' }).click();
  await page.getByRole('button', { name: 'Show: Active Open menu' }).click();
  await page.getByText('All').click();
  await page.getByRole('button', { name: 'Edit or delete condition' }).click();
  await page.getByRole('menuitem', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'danger Delete' }).click();
  await page.getByRole('button', { name: 'Active Visit', exact: true }).click();
  await page.getByRole('button', { name: 'Actions', exact: true }).click();
  await page.getByRole('menuitem', { name: 'End visit' }).click();
  await page.getByRole('button', { name: 'danger End Visit' }).click();
  await page.getByText('Record conditions').click();
  await page.getByPlaceholder('Search conditions').click();
  await page.getByPlaceholder('Search conditions').fill('mental');
  await page.getByRole('menuitem', { name: 'Mental status change' }).click();
  await page.getByLabel('Onset date').click();
  await page.getByLabel('Onset date').fill('04/07/2023');
  await page.getByText('4').nth(1).click();
  await page.getByRole('button', { name: 'Save & close' }).click();
  await page.getByRole('button', { name: 'Edit or delete condition' }).click();
  await page.getByRole('button', { name: 'Show: Active Open menu' }).click();
  await page.getByText('All').click();
  await page.getByRole('button', { name: 'Edit or delete condition' }).click();
  await page.getByRole('menuitem', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'danger Delete' }).click();
});