name: Build

on:
  push:
    branches: [main, 'patch/*']
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  build:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/build-frontend-module.yml@main
    with:
      artifact_path: 'packages/**/dist'
