name: Report bundle size

on:
  pull_request_target:
    branches: [master]

jobs:
  file_size_impact:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx lerna bootstrap
      - name: Report changes
        run: node ./tools/size-reporter.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
